### PR TITLE
Fixes duplication of Linear issue links in the Inspect View

### LINKED ISSUE #4621: Inspect view duplicates Linear issue links instead of replacing
subtask of #4605

A little problem in "Inspect" view: updating status creates a new link rather than updated the same one:

Image

### PR DESCRIPTION
**Pull request by sergeibbb**
# Description
fixes #4621 (#4605)

Normalizes Linear autlink URL by removing summary stubs from its ending

image

Because it was cause of the duplication:

Image

# Checklist

- [x] I have followed the guidelines in the Contributing document
- [x] My changes follow the coding style of this project
- [x] My changes build without any errors or warnings
- [x] My changes have been formatted and linted
- [ ] My changes include any required corresponding changes to the documentation (including CHANGELOG.md and README.md)
- [x] My changes have been rebased and squashed to the minimal number (typically 1) of relevant commits
- [x] My changes have a descriptive commit message with a short title, including a `Fixes $XXX -` or `Closes #XXX -` prefix to auto-close the issue that your PR addresses

### CODE REVIEW

File: src/plus/integrations/providers/linear.ts [hunk 1]
```diff
@@ -259,4 +263,13 @@ export class LinearIntegration extends IssuesIntegration<IssuesCloudHostIntegrat
 			return undefined;
 		}
 	}
+	private getIssueAutolinlikeUrl(issue: ProviderIssue): string | null {
```
Comment (d13) [inline src/plus/integrations/providers/linear.ts]: Nit: did you mean this name?
```suggestion
	private getIssueAutolinkLikeUrl(issue: ProviderIssue): string | null {
```

Comment (sergeibbb) [reply src/plus/integrations/providers/linear.ts]: @d13 Fixed. Anything else?
