### PR TITLE
Handles cancellation of AI commands

### LINKED ISSUE #4354: Improve Explain error messaging
When an "Explain (Branch|Commit|Stash|WIP)" command is ran, the wrong toast messaging can occur. 

Example, if the operation is cancelled due to gating, the toast message will show "No changes to explain".

### PR DESCRIPTION
**Pull request by axosoft-ramint**
Fixes #4354 

- Modifies return output of `sendRequest` and callers up the chain to return (and handle) `'cancelled'` when a cancellation occurs.
- Returns without showing an error message on command-level logic when receiving `'cancelled'` as output.

### CODE REVIEW

File: src/env/node/git/commitMessageProvider.ts [hunk 1]
```diff
@@ -62,7 +62,10 @@ class AICommitMessageProvider implements CommitMessageProvider, Disposable {
 				},
 			);
 
+			if (result === 'cancelled') return;
+
 			if (result == null) return;
+
```
Comment (d13) [inline src/env/node/git/commitMessageProvider.ts]: Nit that's in a few files, otherwise looks good.
```suggestion
			if (result == null || result === 'cancelled') return;

```

Comment (ramin-t) [reply src/env/node/git/commitMessageProvider.ts]: Fixed in commit: https://github.com/gitkraken/vscode-gitlens/pull/4380/commits/ffb03f585cd4d0d851dd2670cd36f0986fd8ecb6
