### PR TITLE
Fixes #708 - Prompt for file path when missing from revision

### LINKED ISSUE #708: open any file from another branch
Recently https://github.com/eamodio/vscode-gitlens/issues/646 was implemented, but it doesn't completely work for me. The reason being that sometimes a file is renamed, and then the command (understandably) fails. In emacs/magit this is handled like that: you run the command, then by default the same filename as your current file is displayed and you just press enter if you want the same filename, but you can edit the filename if needed.

Maybe that gitlens feature, `gitlens.openFileRevisionFromBranch`, could be improved so that if it doesn't find the file in another branch, it doesn't fail but rather gives the user the opportunity to manually specify a filename.

In my case I renamed a `.ts` file to `.tsx`, but there could be many examples of renaming files.

### PR DESCRIPTION
**Pull request by mogelbrod**
# Description

Fixes #708 - Prompt for file path when missing from revision

Improves the `openFileAtRevision()` function by:
- Asking user to enter another path when the requested file doesn't exist in the
  selected revision.
- Showing an error message on subsequent failure (or if an error is thrown).

The above function is used by a number of commands:
- `gitlens.openFileRevision`
- `gitlens.openFileRevisionFrom`
- `gitlens.openRevisionFile`

# Checklist

- [x] I have followed the guidelines in the Contributing document
- [x] My changes follow the coding style of this project
- [x] My changes build without any errors or warnings
- [x] My changes have been formatted and linted
- [x] My changes include any required corresponding changes to the documentation (including CHANGELOG.md and README.md)
- [x] My changes have been rebased and squashed to the minimal number (typically 1) of relevant commits
- [x] My changes have a descriptive commit message with a short title, including a `Fixes $XXX -` or `Closes #XXX -` prefix to auto-close the issue that your PR addresses

### CODE REVIEW

**Comment by mogelbrod** [comment]
Would love to get this reviewed (and hopefully merged) @eamodio 😃

**Comment by mogelbrod** [comment]
Rebased the PR onto the latest main branch again, eagerly awaiting a review 😄

**Comment by eamodio** [comment]
@mogelbrod Thanks for this -- I've started taking a pass through this and having issues with the `OpenFileByRevisionCommand` -- it needs an active editor (though shouldn't really) and the keyboarding doesn't feel right. In GitLens (and VS Code in general), the using the right arrow key in a quick pick, when appropriate, leaves the quick pick open and acts upon the selected item (opening it, etc). This functionality should be moved into the `pickFileAtRevision` quick pick rather than in the refs picker.

But before I dig more into this, I'd love to have the 2 parts split apart. So split out the `OpenFileByRevisionCommand` into a separate PR, as I think there are more UX implications (naming, etc).

File: src/git/actions/commit.ts [hunk 1]
```diff
@@ -440,11 +441,74 @@ export async function openFileAtRevision(
...
+			);
+		});
+
+		return pick
+			? Container.instance.git.getRevisionUri(uri.sha!, `${uri.repoPath}/${pick}`, uri.repoPath!)
+			: undefined;
+	} finally {
+		disposables.forEach(d => {
+			d.dispose();
+		});
```
Comment (eamodio) [inline src/git/actions/commit.ts:511]: Let's move this into `src/quickpicks/revisionPicker.ts` similar to the other pickers

File: src/git/actions/commit.ts [hunk 2]
```diff
@@ -440,11 +441,74 @@ export async function openFileAtRevision(
...
+	const disposables: Disposable[] = [];
+	try {
+		const picker = window.createQuickPick();
+		Object.assign(picker, {
+			title: options.title,
+			value: options.initialPath ?? uri.relativePath,
+			placeholder: 'Enter path to file...',
+			busy: true,
+			ignoreFocusOut: getQuickPickIgnoreFocusOut(),
+		});
```
Comment (eamodio) [inline src/git/actions/commit.ts:487]: Please set the props directly -- avoid `Object.assign`

File: src/git/actions/commit.ts [hunk 3]
```diff
@@ -440,11 +441,74 @@ export async function openFileAtRevision(
...
+		picker.show();
+
+		const tree = await Container.instance.git.getTreeForRevision(uri.repoPath, uri.sha!);
+		picker.items = tree.filter(file => file.type === 'blob').map((file): QuickPickItem => ({ label: file.path }));
```
Comment (eamodio) [inline src/git/actions/commit.ts:491]: Use `filterMap` from `iterable.ts` to avoid filtering and mapping separately

Comment (eamodio) [inline src/git/actions/commit.ts:491]: I'd like to try only putting the base filename as the label and putting the rest of the folder path in the description -- closer to the vscode picker. Will need to enable `picker.matchOnDescription` as well.

File: src/git/actions/commit.ts [hunk 4]
```diff
@@ -440,11 +441,74 @@ export async function openFileAtRevision(
...
+		const pick = await new Promise<string | undefined>(resolve => {
+			disposables.push(
+				picker,
+				picker.onDidHide(() => resolve(undefined)),
+				picker.onDidAccept(() => {
+					if (picker.activeItems.length === 0) return;
+					resolve(picker.activeItems[0].label);
+				}),
+			);
+		});
```
Comment (eamodio) [inline src/git/actions/commit.ts:503]: It would be nice to add the extra keyboard (right arrow) support here to open the selected file in a preview editor.

**Review by eamodio — CHANGES_REQUESTED** [review]

File: src/git/actions/commit.ts (hunk 4 above)
Comment (mogelbrod) [reply src/git/actions/commit.ts:503]: I didn't know about this functionality 😄 Not sure how though, do you have any pointers to existing implementations?

Would it potentially break text selections using left/right arrow keys in the text field?

File: src/git/actions/commit.ts (hunk 1 above)
Comment (mogelbrod) [reply src/git/actions/commit.ts:511]: Sure! Should it be called `fileRevisionPicker` (or a variation thereof) or `revisionPicker`? I'm leaning towards the former since it's technically picking a file at a specific revision, rather than picking a revision (unless the "file" part is implicit for revisions?).

File: src/quickpicks/revisionPicker.ts [hunk 5]
```diff
@@ -0,0 +1,58 @@
...
+		picker.show();
+
+		const tree = await Container.instance.git.getTreeForRevision(uri.repoPath, uri.sha!);
+		picker.items = Array.from(filterMap(tree, file => {
+			// Exclude directories
+			if (file.type !== 'blob') { return null }
+			return { label: file.path }
+			// FIXME: Remove this unless we opt to show the directory in the description
+			// const parsed = path.parse(file.path)
+			// return { label: parsed.base, description: parsed.dir }
```
Comment (mogelbrod) [inline src/quickpicks/revisionPicker.ts:35]: Left this code in if you wanted to try it out yourself @eamodio. It does depend on `path`, which appears to be a forbidden import.

**Comment by mogelbrod** [comment]
Thanks for taking the time to dig into this @eamodio!

I've extracted the `openFileByRevision` command addition into [a separate PR](https://github.com/gitkraken/vscode-gitlens/pull/3036). It's currently marked as draft - I'll update it to reflect all changes once this PR lands in `main`.
