### PR TITLE
Fixes selection highlight delay when selecting composer commits with large commits

### LINKED ISSUE #4872: Recompose performance degrades when each commit is selected
In a UX session with Eric, we discovered that composer takes longer to render changes as more commits are selected during recomposition.

### PR DESCRIPTION
**Pull request by ramin-t**
Closes #4872

Reduces the time needed to highlight a commit in the commits panel of the composer when it is selected or shift-selected.

Does this by:
1. Using caching/memoization to reduce redundant calculations of commits and hunks and diff/file counts in both the app and commits panel.
2. Delaying the event firing from the commits panel to the app using double-RAF
3. Fixing some redundant processing that happens on diff files when initially loaded, and uses scheduling for updates
4. Removing the transition from commit highlighting when selected

### CODE REVIEW

File: src/webviews/apps/plus/composer/components/app.ts [hunk 1]
```diff
@@ -1202,12 +1202,22 @@ export class ComposerApp extends LitElement {
...
+
 	private get hunksWithAssignments(): ComposerHunk[] {
 		if (!this.state?.hunks || !this.state?.commits) {
 			return [];
 		}
 
-		return updateHunkAssignments(this.state.hunks, this.state.commits);
+		const { hunks, commits } = this.state;
+		const cached = this._hunksWithAssignmentsCache;
+		if (cached?.hunks === hunks && cached?.commits === commits) {
```
[the remark this answers is not in the document]
Comment (ramin-t) [reply src/webviews/apps/plus/composer/components/app.ts:1214]: We don't mutate hunk content in-place, so this should be fine.

**Comment by ramin-t** [comment]
augment review

**Comment by ramin-t** [comment]
augment review

File: src/webviews/apps/plus/composer/components/commits-panel.ts [hunk 2]
```diff
@@ -925,14 +1008,38 @@ export class CommitsPanel extends LitElement {
...
+	 * (e.g. rendering diffs in the details panel).
+	 */
+	private dispatchAfterPaint(event: Event) {
+		const gen = ++this._pendingDispatch;
+		requestAnimationFrame(() => {
+			requestAnimationFrame(() => {
+				if (gen !== this._pendingDispatch || !this.isConnected) return;
+				this.dispatchEvent(event);
+			});
+		});
```
Comment (d13) [inline src/webviews/apps/plus/composer/components/commits-panel.ts]: Does the double `requestAnimationFrame` provide better efficiency/performance over using `setTimeout(0)`?

**Review by d13 — APPROVED** [review]
Looks good, but was curious about using double `requestAnimationFrame` versus using `setTimeout(0)`.

File: src/webviews/apps/plus/composer/components/commits-panel.ts (hunk 2 above)
Comment (ramin-t) [reply src/webviews/apps/plus/composer/components/commits-panel.ts]: I had initially thought doubleRAF had a better guarantee of the logic hitting the exact timing I wanted before your comment, but after doing a bit of research, it looks like setTimeout(0) should get us there (past the first paint) pretty reliably and might even be a touch faster, so I'll switch to it. Thanks!
