### PR TITLE
Closes #1550 - allow force-push for non-HEAD commits and from commit widget

### LINKED ISSUE #1550: Push button in commit widget does not trigger "Push force" when ALT is pressed.
- GitLens Version: v11.5.1
- Git Version: git version 2.31.1.windows.1

- VSCode Version: 1.57.1
507ce72a4466fbb27b715c3722558bb15afa9f48
x64
- OS Version: Windows 10 21H1 19043.1052

Steps to Reproduce:

1. Make a rebase or a commit ammend, or whatever requiring a push force
2. in the GITLENS:COMMITS widget press ALT and click on the Push button

What I See:
- when i press ALT, the icon of the push button changes, indicating that the ALT key is taken into account
- an error window popup: `Can't push refs to remote. Try running 'Pull' first to integrate your changes`

Show command output: 
```
> git push origin <branch_name>:<branch_name>
To ssh://hostname/user/repo
 ! [rejected]            <branch_name> -> <branch_name> (non-fast-forward)
error: failed to push some refs to 'ssh://hostname/user/repo'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

GITLENS logs: 
```
[2021-06-18 09:22:35:094] [124c] ViewCommands.push — t=BranchTrackingStatusNode(gitlens:repository(s:/..../..../....):branch(<branch_name>):root:status-branch:upstream(origin/<branch_name>):ahead), u=true
[2021-06-18 09:22:35:095] [124e] GitService.getOrderedRepositories
[2021-06-18 09:22:35:095] [124f] GitService.getRepositories
[2021-06-18 09:22:35:095] [124f] GitService.getRepositories completed • 0 ms
[2021-06-18 09:22:35:095] [124e] GitService.getOrderedRepositories completed • 0 ms
[2021-06-18 09:22:35:096] [1250] GitService.pushAll — v=salt-group-states, O={"force":false}
[2021-06-18 09:22:35:096] [1251] Repository(s:/..../..../....).push — {"force":false}
[2021-06-18 09:22:35:102] [124d] GitCommandsCommand.execute completed
[2021-06-18 09:22:35:102] [124c] ViewCommands.push completed • 7 ms
[2021-06-18 09:22:35:648] [1252] GitService.onWindowStateChanged — v={"focused":false}
[2021-06-18 09:22:35:648] [1252] GitService.onWindowStateChanged completed • 0 ms
[2021-06-18 09:22:40:137] [1253] CommitsView.triggerNodeChange — l=CommitsViewNode
[2021-06-18 09:22:40:138] [1253] CommitsView.triggerNodeChange completed • 0 ms
[2021-06-18 09:22:40:146] [1254] CommitsRepositoryNode(gitlens:repository(s:/..../..../....)).ensureSubscription
[2021-06-18 09:22:40:146] [1254] CommitsRepositoryNode(gitlens:repository(s:/..../..../....)).ensureSubscription completed • 0 ms
[2021-06-18 09:22:40:147] [1255] GitService.getRepository — v=s:/..../..../....
[2021-06-18 09:22:40:147] [1256] GitService.getRepository — v=s:/..../..../....
[2021-06-18 09:22:40:170] [1255] GitService.getRepository returned s:/..../..../.... • 23 ms
[2021-06-18 09:22:40:171] [1256] GitService.getRepository returned s:/..../..../.... • 23 ms
[2021-06-18 09:22:44:335] [1257] GitService.onWindowStateChanged — v={"focused":true}
[2021-06-18 09:22:44:335] [1257] GitService.onWindowStateChanged completed • 0 ms
[2021-06-18 09:22:44:337] [1258] Repository(s:/.../.../.../).fireChange — unknown
[2021-06-18 09:22:44:337] [1258] Repository(s:/.../.../.../).fireChange completed • 0 ms
[2021-06-18 09:22:44:337] [1251] Repository(s:/.../.../.../).push completed • 9241 ms
[2021-06-18 09:22:44:337] [1250] GitService.pushAll completed • 9241 ms
[2021-06-18 09:22:44:380] [1259] GitUri.fromUri — f=Uri(git-output:/git-error-1624008164337)
[2021-06-18 09:22:44:381] [1259] GitUri.fromUri returned GitUri(git-output:/git-error-1624008164337) • 0 ms
[2021-06-18 09:22:44:381] [125a] GitService.getRepository — v=GitUri(git-output:/git-error-1624008164337)
[2021-06-18 09:22:44:381] [125b] GitService.findRepositoryForPath — v=count=1, O=\git-error-1624008164337, W=false
[2021-06-18 09:22:44:381] [125b] GitService.findRepositoryForPath completed • 0 ms
[2021-06-18 09:22:44:381] [125a] GitService.getRepository returned undefined • 0 ms
[2021-06-18 09:22:44:381] [125c] GitService.isTracked returned false • 0 ms — v=GitUri(git-output:/git-error-1624008164337)
[2021-06-18 09:22:44:381] [125d] LineAnnotationController.onActiveLinesChanged — t=editor=git-output:/git-error-1624008164337, selections=undefined, pending=true, reason=editor
[2021-06-18 09:22:44:381] [125e] LineAnnotationController.clear completed • 0 ms
[2021-06-18 09:22:44:381] [125d] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2021-06-18 09:22:44:381] [125f] LineHoverController.onActiveLinesChanged — t=editor=git-output:/git-error-1624008164337, selections=undefined, pending=true, reason=editor
[2021-06-18 09:22:44:381] [125f] LineHoverController.onActiveLinesChanged completed • 0 ms
[2021-06-18 09:22:44:381] [1260] StatusBarController.onActiveLinesChanged — t=editor=git-output:/git-error-1624008164337, selections=undefined, pending=true, reason=editor
[2021-06-18 09:22:44:381] [1260] StatusBarController.onActiveLinesChanged completed • 0 ms
[2021-06-18 09:22:44:600] Repository(s:/.../.../.../) firing changes=unknown
[2021-06-18 09:22:44:605] [1262] CommitsRepositoryNode(gitlens:repository(s:/.../.../...)).onRepositoryChanged — D={ repository: salt-group-states, changes: unknown }
[2021-06-18 09:22:44:605] [1263] CommitsRepositoryNode(gitlens:repository(s:/.../.../...)).triggerChange — true
[2021-06-18 09:22:44:605] [1264] CommitsRepositoryNode(gitlens:repository(s:/.../.../...)).triggerChange — true, false
[2021-06-18 09:22:44:605] [1265] CommitsViewNode.triggerChange — true, false
[2021-06-18 09:22:44:605] [1266] CommitsView.refreshNode — l=CommitsViewNode, j=true, p=false
[2021-06-18 09:22:44:605] [1267] CommitsViewNode.refresh — true
[2021-06-18 09:22:44:605] [1268] CommitsRepositoryNode(gitlens:repository(s:/.../.../...)).dispose
[2021-06-18 09:22:44:605] [1269] CommitsRepositoryNode(gitlens:repository(s:/.../.../...)).unsubscribe
[2021-06-18 09:22:44:605] [1268] CommitsRepositoryNode(gitlens:repository(s:/.../.../...)).dispose completed • 0 ms
[2021-06-18 09:22:44:605] [1267] CommitsViewNode.refresh completed • 0 ms
[2021-06-18 09:22:44:605] [1262] CommitsRepositoryNode(gitlens:repository(s:/.../.../...)).onRepositoryChanged completed • 0 ms
[2021-06-18 09:22:44:606] [126a] CommitsView.triggerNodeChange — l=CommitsViewNode
[2021-06-18 09:22:44:606] [126a] CommitsView.triggerNodeChange completed • 0 ms
[2021-06-18 09:22:44:606] [1269] CommitsRepositoryNode(gitlens:repository(s:/.../.../...)).unsubscribe completed • 1 ms
[2021-06-18 09:22:44:607] [1266] CommitsView.refreshNode completed • 1 ms
[2021-06-18 09:22:44:607] [1265] CommitsViewNode.triggerChange completed • 1 ms
[2021-06-18 09:22:44:607] [1264] CommitsRepositoryNode(gitlens:repository(s:/.../.../...)).triggerChange completed • 2 ms
[2021-06-18 09:22:44:607] [1263] CommitsRepositoryNode(gitlens:repository(s:/.../.../...)).triggerChange completed • 2 ms
[2021-06-18 09:22:44:610] [126b] GitService.getOrderedRepositories
[2021-06-18 09:22:44:610] [126c] GitService.getRepositories
[2021-06-18 09:22:44:610] [126c] GitService.getRepositories completed • 0 ms
[2021-06-18 09:22:44:610] [126b] GitService.getOrderedRepositories completed • 0 ms
[2021-06-18 09:22:44:613] [126d] CommitsRepositoryNode(gitlens:repository(s:/.../.../...)).ensureSubscription
[2021-06-18 09:22:44:613] [126e] CommitsRepositoryNode(gitlens:repository(s:/.../.../...)).subscribe
[2021-06-18 09:22:44:613] [126f] GitService.getBranchAheadRange — v=<branch_name>
[2021-06-18 09:22:44:613] [126f] GitService.getBranchAheadRange completed • 0 ms
[2021-06-18 09:22:44:613] [1270] GitService.getLog — v=s:/.../.../..., {"limit":40,"ref":"<branch_name>"}
[2021-06-18 09:22:44:618] [1271] GitService.getBranchesAndTagsTipsFn — v=s:/.../.../..., O=<branch_name>
[2021-06-18 09:22:44:618] [1272] GitService.getBranches — v=s:/.../.../...
[2021-06-18 09:22:44:618] [1273] GitService.getTags — v=s:/.../.../...
[2021-06-18 09:22:44:618] [1274] GitService.getStatusForRepo — v=s:/.../.../...
[2021-06-18 09:22:44:623] [1275] GitService.getMergeStatus — v=s:/.../.../...
[2021-06-18 09:22:44:623] [1276] GitService.getRebaseStatus — v=s:/.../.../...
[2021-06-18 09:22:44:623] [1277] GitBranch.getAssociatedPullRequest — L={"include":["Open","Merged"]}
[2021-06-18 09:22:44:623] [1278] GitService.getLogRefsOnly — v=s:/.../.../..., {"limit":0,"ref":"origin/<branch_name>..<branch_name>"}
[2021-06-18 09:22:44:627] [1275] GitService.getMergeStatus completed • 4 ms
[2021-06-18 09:22:44:627] [1276] GitService.getRebaseStatus completed • 4 ms
[2021-06-18 09:22:44:627] [1279] GitService.getPullRequestForBranch — v=<branch_name>, O=origin, {"include":["Open","Merged"]}
[2021-06-18 09:22:44:627] [1272] GitService.getBranches completed • 9 ms
[2021-06-18 09:22:44:627] [1273] GitService.getTags completed • 8 ms
[2021-06-18 09:22:44:627] [1279] GitService.getPullRequestForBranch completed • 0 ms
[2021-06-18 09:22:44:628] [1271] GitService.getBranchesAndTagsTipsFn completed • 9 ms
[2021-06-18 09:22:44:628] [1277] GitBranch.getAssociatedPullRequest completed • 5 ms
[2021-06-18 09:22:44:631] [127a] GitLineTracker.updateState returned false • document is not blameable • 0 ms — t=0, u=git-output:/git-error-1624008164337
[2021-06-18 09:22:44:632] [127b] LineAnnotationController.onActiveLinesChanged — t=editor=git-output:/git-error-1624008164337, selections=undefined, pending=false, reason=editor
[2021-06-18 09:22:44:632] [127c] LineAnnotationController.clear completed • 0 ms
[2021-06-18 09:22:44:632] [127b] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2021-06-18 09:22:44:632] [127d] LineHoverController.onActiveLinesChanged — t=editor=git-output:/git-error-1624008164337, selections=undefined, pending=false, reason=editor
[2021-06-18 09:22:44:632] [127d] LineHoverController.onActiveLinesChanged completed • 0 ms
[2021-06-18 09:22:44:632] [127e] StatusBarController.onActiveLinesChanged — t=editor=git-output:/git-error-1624008164337, selections=undefined, pending=false, reason=editor
[2021-06-18 09:22:44:632] [127e] StatusBarController.onActiveLinesChanged completed • 0 ms
[2021-06-18 09:22:44:632] [127f] CommitsRepositoryNode(gitlens:repository(s:/.../.../...)).subscribe
[2021-06-18 09:22:44:632] [127f] CommitsRepositoryNode(gitlens:repository(s:/.../.../...)).subscribe completed • 0 ms
[2021-06-18 09:22:44:633] [126e] CommitsRepositoryNode(gitlens:repository(s:/.../.../...)).subscribe completed • 19 ms
[2021-06-18 09:22:44:633] [126d] CommitsRepositoryNode(gitlens:repository(s:/.../.../...)).ensureSubscription completed • 19 ms
[2021-06-18 09:22:44:660] [s:/.../.../...] git ls-files -- s:\...\...\...\...\...\...\...-...-...\....cfg • 59 ms 
[2021-06-18 09:22:44:660] [1261] GitService.isTracked returned true • 60 ms — v=GitUri(file:///s:/.../.../.../.../.../.../.../....cfg repoPath=s:/.../.../...)
[2021-06-18 09:22:44:678] [s:/.../.../...] git log --format=%x3cr%x3e%x20%H --full-history -M -m origin/<branch_name>..<branch_name> -- • 55 ms 
[2021-06-18 09:22:44:678] [1280] GitLogParser.parseRefsOnly
[2021-06-18 09:22:44:678] [1280] GitLogParser.parseRefsOnly completed • 0 ms
[2021-06-18 09:22:44:678] [1278] GitService.getLogRefsOnly completed • 55 ms
[2021-06-18 09:22:44:687] [s:/.../.../...] git log --format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cc%x3e%x20%ct%n%x3cp%x3e%x20%P%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e%n%x3cf%x3e --full-history -M -m --name-status -n41 <branch_name> -- • 73 ms 
[2021-06-18 09:22:44:687] [1281] GitService.getCurrentUser — s:/.../.../...
[2021-06-18 09:22:44:687] [1281] GitService.getCurrentUser completed • 0 ms
[2021-06-18 09:22:44:687] [1282] GitLogParser.parse
[2021-06-18 09:22:44:688] [1282] GitLogParser.parse completed • 0 ms
[2021-06-18 09:22:44:688] [1270] GitService.getLog completed • 74 ms
[2021-06-18 09:22:44:693] [s:/.../.../...] git status --porcelain=v2 --branch -u --find-renames -- • 74 ms 
[2021-06-18 09:22:44:693] [1284] GitStatusParser.parseV2 completed • 0 ms
[2021-06-18 09:22:44:693] [1283] GitStatusParser.parse completed • 0 ms
[2021-06-18 09:22:44:693] [1274] GitService.getStatusForRepo completed • 74 ms
[2021-06-18 09:22:44:694] [1285] GitService.getRepository — v=s:/.../.../...
[2021-06-18 09:22:44:694] [1286] GitService.getRepository — v=s:/.../.../...
[2021-06-18 09:22:44:701] [1285] GitService.getRepository returned s:/.../.../... • 7 ms
[2021-06-18 09:22:44:702] [1286] GitService.getRepository returned s:/.../.../... • 7 ms
[2021-06-18 09:23:14:638] [1287] CommitsView.triggerNodeChange — l=CommitsViewNode
[2021-06-18 09:23:14:638] [1287] CommitsView.triggerNodeChange completed • 0 ms
[2021-06-18 09:23:14:644] [1288] CommitsRepositoryNode(gitlens:repository(s:/.../.../...)).ensureSubscription
[2021-06-18 09:23:14:644] [1288] CommitsRepositoryNode(gitlens:repository(s:/.../.../...)).ensureSubscription completed • 0 ms
[2021-06-18 09:23:14:644] [1289] GitService.getRepository — v=s:/.../.../...
[2021-06-18 09:23:14:644] [128a] GitService.getRepository — v=s:/.../.../...
[2021-06-18 09:23:14:653] [1289] GitService.getRepository returned s:/.../.../... • 8 ms
[2021-06-18 09:23:14:653] [128a] GitService.getRepository returned s:/.../.../... • 8 ms
```
```
[2021-06-18 09:22:44:660] [s:/.../.../...] git ls-files -- s:\...\...\...\...\...\...\...\....cfg • 59 ms 
[2021-06-18 09:22:44:678] [s:/.../.../...] git log --format=%x3cr%x3e%x20%H --full-history -M -m origin/<branch_name>..<branch_name> -- • 55 ms 
[2021-06-18 09:22:44:687] [s:/.../.../...] git log --format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cc%x3e%x20%ct%n%x3cp%x3e%x20%P%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e%n%x3cf%x3e --full-history -M -m --name-status -n41 <branch_name> -- • 73 ms 
[2021-06-18 09:22:44:693] [s:/.../.../...] git status --porcelain=v2 --branch -u --find-renames -- • 74 ms 
```
Built in VSCode push force works as intended.

### PR DESCRIPTION
**Pull request by ShafinKhadem**
# Description

Closes #1550. Force-push was also not working for non-HEAD commits in branches view. To fix these, I had to update [git API from the VS Code repo](https://github.com/microsoft/vscode/blob/main/extensions/git/src/api/git.d.ts) as I needed `force` parameter for `repo.push`.

I was also experiencing 2 exceptions before any of my changes - one for circular reference, another for null pr. I have handled them as well.

# Checklist

- [x] I have followed the guidelines in the Contributing document
- [x] My changes follow the coding style of this project
- [x] My changes build without any errors or warnings
- [x] My changes have been formatted and linted
- [x] My changes include any required corresponding changes to the documentation (including CHANGELOG.md and README.md)
- [x] My changes have been rebased and squashed to the minimal number (typically 1) of relevant commits
- [x] My changes have a descriptive commit message with a short title, including a `Fixes $XXX -` or `Closes #XXX -` prefix to auto-close the issue that your PR addresses

### CODE REVIEW

File: src/plus/github/github.ts [hunk 1]
```diff
@@ -458,7 +458,7 @@ export class GitHubApi implements Disposable {
 
 			// If the pr is not from a fork, keep it e.g. show root pr's on forks, otherwise, ensure the repo owners match
 			const prs = rsp?.repository?.refs.nodes[0]?.associatedPullRequests?.nodes?.filter(
-				pr => !pr.repository.isFork || pr.repository.owner.login === owner,
+				pr => pr != null && (!pr.repository.isFork || pr.repository.owner.login === owner),
```
Comment (eamodio) [inline src/plus/github/github.ts:461]: Please undo this -- I'll check this in separately (as its unrelated to this changeset)

File: src/system/decorators/resolver.ts [hunk 2]
```diff
@@ -2,6 +2,7 @@ import { Uri } from 'vscode';
 
 function replacer(key: string, value: any): any {
 	if (key === '') return value;
+	if (key == 'container') return undefined;	// container may contain circular references.
```
Comment (eamodio) [inline src/system/decorators/resolver.ts:5]: For this one -- I tried making this change, but couldn't get it to hit this case -- when are you seeing it? I ask because this isn't really the right fix -- it implies that something is passing a rich object through a decorator, which shouldn't be happening.

**Review by eamodio — CHANGES_REQUESTED** [review]
@ShafinKhadem Thanks! I've added some comments and requested a couple of minor changes.

File: src/git/models/repository.ts [hunk 3]
```diff
@@ -782,7 +783,7 @@ export class Repository implements Disposable {
 				const branch = await this.getBranch();
 				if (branch == null) return;
 
-				await repo?.push(branch.getRemoteName(), `${options.reference.ref}:${branch.getNameWithoutRemote()}`);
+				await repo?.push(branch.getRemoteName(), `${options.reference.ref}:${branch.getNameWithoutRemote()}`, undefined, options?.force ? ForcePushMode.ForceWithLease : undefined);
```
[the remark this answers is not in the document]
Comment (ShafinKhadem) [reply src/git/models/repository.ts:786]: Done.

File: src/plus/github/github.ts (hunk 1 above)
Comment (ShafinKhadem) [reply src/plus/github/github.ts]: Done. I face this exception quite frequently but this is handled already by try catch.

File: src/system/decorators/resolver.ts (hunk 2 above)
Comment (ShafinKhadem) [reply src/system/decorators/resolver.ts]: Removed this for now. Will open a new issue if I can reproduce this.

**Comment by ShafinKhadem** [comment]
@eamodio I have addressed the requested changes. Thanks.

**Comment by eamodio** [comment]
Thank you so much for your contribution!

Thank you!

**Comment by ShafinKhadem** [comment]
@eamodio Now that non-HEAD commits can be force-pushed, should I add a `pushToCommitWithForce` view? Even though I don't think `gitlens.views.pushWithForce` is that useful as `gitlens.views.push` automatically detects when force is needed, maybe it's better to have the `[Alt] Push (force)` for new users?

**Comment by eamodio** [comment]
@ShafinKhadem Hrm, if I am understanding correctly, you are asking about adding a new "Push to Commit (Force)" command to the right-click of commits? If so, I don't think that it necessary since "Push to Commit" already handles that case.

**Comment by ShafinKhadem** [comment]
@eamodio I meant this [Alt] Push (Force) for HEAD commits:

image

For non-head commits it's not available:

image
